name: "Nitro build tool for IOS"
description: "A Gihub Action for building React Native apps with Nitro"
branding:
  icon: "zap"
  color: "gray-dark"
inputs:
  # Basic configuration
  root-directory:
    description: The directory within your project, in which your code is located. Leave this field empty if your code is not located in a subdirectory"
    default: "./"
  ios-scheme:
    description: "The name of the iOS scheme"
  ios-xcconfig-path:
    description: "Path to a custom xcconfig file. The path relative to project root directory where the custom `.xcconfig` file is located"

  # App Versioning
  version-name:
    description: "The version name for the app"
  version-code:
    description: "The version code for the app"
  disable-version-name-from-package-json:
    description: "Disable automatic version name configuration. By default will get the 'version' field from package.json and set the version name. Available Options: (`yes` / `no`)"
  disable-version-code-auto-generation:
    description: "Disable automatic version code generation. By default will generate a timestamp based number and set the version code. Available Options: (`yes` / `no`)"

  # App Signing
  ios-certificate-url:
    description: "Certificate url. The url to download and install the certificate"
  ios-certificate-base64:
    description: "Certificate base64. The certificate base64 string enconded."
  ios-certificate-passphrase:
    description: "Certificate passphrase"
  ios-codesigning-identity:
    description: "Codesigning identity"
  ios-provisioning-profile-urls:
    description: "Provisioning profile urls. A string containing a '|' separated values where provisioning profiles are located (e.g. `url1|url2``)"
  ios-provisioning-profiles-base64:
    description: "Provisioning profiles in base64 format. A string containing a '|' separated values with provisioning profiles base64 encoded (e.g. `bXktcHJvdmlzaW9uaW5nLXByb2ZpbGUtY29udGVudC0x|bXktcHJvdmlzaW9uaW5nLXByb2ZpbGUtY29udGVudC0y`)"
  ios-provisioning-profile-specifier:
    description: "Provisioning profile specifier. The name of the provisioning profile when using a single one"
  ios-team-id:
    description: "Team ID. Specify the Team ID you want to use for the Apple Developer Portal"
  ios-export-method:
    description: "Export Method. The export method used to generate the IPA. Available Options: (`ad-hoc` / `app-store`)"
    default: "ad-hoc"

  # Caching
  cache-provider:
    description: "Cache provider where cache artifacts will be persisted. Available Options: (`fs`: File system / `github`: Uses Github cache action / `s3`: Amazon - Simple Storage Service)"
    default: "github"
  disable-cache:
    description: "When setting this option to `yes` build cache optimizations won't be performed.  Available Options: (`yes` / `no`)"
  cache-env-var-lookup-keys:
    description: "List of env var keys for lookup to determine cache fingerprint. A list of `\\|` separated values with env variable keys to lookup to determine whether the build should be cached or not"
  cache-file-lookup-paths:
    description: "List of files for lookup to determine cache fingerprint. A list of `\\|` separated value paths (relative to the root of the repo or absolute) to lookup in order to determine whether the build should be cached or not"
  disable-metro-cache:
    description: "Setting this field to yes will disable the React Native Metro cache feature"

  # Hooks
  pre-install-command:
    description: "Run command prior to install project dependencies (e.g. `rm -rf ./some-folder`)"

  pre-build-command:
    description: "Run command prior to start building the app (e.g. `yarn tsc && yarn test`)"

  post-build-command:
    description: "Run command once build successfully finished (e.g. `yarn publish`)"

  # Advanced
  output-directory:
    description: "The path to the directory where to place all of Nitro's output files"
  entry-file:
    description: "The entry file for bundle generation"
  debug:
    description: "Enable verbose logs. Available Options: (`yes` / `no`)"
  fail-safe:
    description: "Runing the app in this mode allows you to prevent the build to fail but you can check the status in further steps"
outputs:
  nitro-build-status:
    description: "The status of the latest build (success / failure)"
    value: ${{ steps.nitro-cli.outputs.nitro-build-status }}
  nitro-output-dir:
    description: "The path to the directory where to place all of Nitro's output files"
    value: ${{ steps.nitro-cli.outputs.nitro-output-dir }}
  nitro-logs-path:
    description: "The full path to access the build log"
    value: ${{ steps.nitro-cli.outputs.nitro-logs-path }}
  nitro-deploy-path:
    description: "The full path to access the build artifacts"
    value: ${{ steps.nitro-cli.outputs.nitro-deploy-path }}
  nitro-summary-path:
    description: "The full path to access the build summary report"
    value: ${{ steps.nitro-cli.outputs.nitro-summary-path }}
runs:
  using: "composite"
  steps:
    # - name: Setup Ruby
    #   if: ${{ hashFiles('.ruby-version') != '' }}
    #   uses: ruby/setup-ruby@v1
    # - name: Install envman
    #   shell: bash
    #   run: |
    #     curl -fL https://github.com/bitrise-io/envman/releases/download/2.3.3/envman-"$(uname -s)"-"$(uname -m)" > /usr/local/bin/envman
    #     chmod +x /usr/local/bin/envman
    # - name: Update Homebrew
    #   shell: bash
    #   run: |
    #     brew update --preinstall
    #     cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/fastlane.rb" "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/pigz.rb" > .github/brew-formulae
    # - name: Configure Homebrew cache
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/Library/Caches/Homebrew/fastlane--*
    #       ~/Library/Caches/Homebrew/downloads/*--fastlane-*
    #       ~/Library/Caches/Homebrew/pigz--*
    #       ~/Library/Caches/Homebrew/downloads/*--pigz-*
    #     key: brew-${{ hashFiles('.github/brew-formulae') }}
    #     restore-keys: brew-
    # - name: Install Homebrew dependencies
    #   shell: bash
    #   run: |
    #     env HOMEBREW_NO_AUTO_UPDATE=1 brew install fastlane pigz
    - name: Configure Nitro Cache
      uses: actions/cache@v2
      if: ${{ inputs.cache-provider == 'github' }}
      with:
        path: |
          ~/.nitro/cache/*
        key: ${{ runner.os }}-nitro-cache
        restore-keys: ${{ runner.os }}-nitro-cache
    - name: Run Nitro cli
      id: nitro-cli
      shell: bash
      run: |
        set -e

        if [[ "${{ inputs.fail-safe }}" == "true" || "${{ inputs.fail-safe }}" == "yes" ]]; then
          set +e
        fi

        # shellcheck disable=SC2154
        if [[ "${{ inputs.debug }}" == "true" || "${{ inputs.debug }}" == "yes" ]]; then
          set -x
        fi

        if [[ -n "${{ inputs.entry-file }}" ]]; then
          export ENTRY_FILE="${{ inputs.entry-file }}"
        fi

        # Obtain vm boot time

        ##########################
        # TODO: Obtain boot time
        ##########################

        # Build command arguments
        args=("ios")
        args+=("--tracking-provider" "nitro-on-premise")

        # shellcheck disable=SC2154
        if [[ "${{ inputs.debug }}" == "true" || "${{ inputs.debug }}" == "yes" ]]; then
          args+=("--verbose")
        fi

        args+=("--build-id" "${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}")
        args+=("--repo-path" "${GITHUB_WORKSPACE}")

        # -------------------
        # Basic configuration
        # -------------------

        if [[ -n "${{ inputs.root-directory }}" ]]; then
          args+=("--root-directory" "${{ inputs.root-directory }}")
        fi

        if [[ -n "${{ inputs.ios-scheme }}" ]]; then
          args+=("--ios-scheme" "${{ inputs.ios-scheme }}")
        fi

        if [[ -n "${{ inputs.ios-xcconfig-path }}" ]]; then
          args+=("--ios-xcconfig-path" "${{ inputs.ios-xcconfig-path }}")
        fi

        # --------------
        # App Versioning
        # --------------

        if [[ -n "${{ inputs.version-name }}" ]]; then
          args+=("--version-name" "${{ inputs.version-name }}")
        fi

        if [[ -n "${{ inputs.version-code }}" ]]; then
          args+=("--version-code" "${{ inputs.version-code }}")
        fi

        # shellcheck disable=SC2154
        if [[ "${{ inputs.disable-version-name-from-package-json }}" == "true" || "${{ inputs.disable-version-name-from-package-json }}" == "yes" ]]; then
          args+=("--disable-version-name-from-package-json")
        fi

        # shellcheck disable=SC2154
        if [[ "${{ inputs.disable-version-code-auto-generation }}" == "true" || "${{ inputs.disable-version-code-auto-generation }}" == "yes" ]]; then
          args+=("--disable-version-code-auto-generation")
        fi

        # -----------
        # App Signing
        # -----------

        if [[ -n "${{ inputs.ios-certificate-base64 }}" && -n "${{ inputs.ios-certificate-url }}" ]]; then
          echo "⚠️ You cannot provide both: 'ios-certificate-base64' and 'ios-certificate-url'"
          exit 1
        fi

        if [[ -z "${{ inputs.ios-certificate-base64 }}" && -z "${{ inputs.ios-certificate-url }}" ]]; then
          echo "⚠️ You must provide at least one of these arguments: 'ios-certificate-base64', 'ios-certificate-url'"
          exit 1
        fi

        if [[ -n "${{ inputs.ios-certificate-base64 }}" ]]; then
          echo -n "${{ inputs.ios-certificate-base64 }}" | base64 --decode --output "${RUNNER_TEMP}/certificate.p12"
          args+=("--ios-certificate-url" "file://${RUNNER_TEMP}/certificate.p12")
        else
          args+=("--ios-certificate-url" "${{ inputs.ios-certificate-url }}")
        fi

        if [[ -n "${{ inputs.ios-certificate-passphrase }}" ]]; then
          args+=("--ios-certificate-passphrase" "${{ inputs.ios-certificate-passphrase }}")
        fi

        if [[ -n "${{ inputs.ios-codesigning-identity }}" ]]; then
          args+=("--ios-codesigning-identity" "${{ inputs.ios-codesigning-identity }}")
        fi

        if [[ -n "${{ inputs.ios-provisioning-profile-urls }}" && -n "${{ inputs.ios-provisioning-profiles-base64 }}" ]]; then
          echo "⚠️ You cannot provide both 'ios-provisioning-profile-urls' and 'ios-provisioning-profiles-base64'"
          exit 1
        fi

        if [[ -z "${{ inputs.ios-provisioning-profile-urls }}" && -z "${{ inputs.ios-provisioning-profiles-base64 }}" ]]; then
          echo "⚠️ You must provide at least one of these arguments: 'ios-provisioning-profile-urls', 'ios-provisioning-profiles-base64'"
          exit 1
        fi

        if [[ -n "${{ inputs.ios-provisioning-profile-urls }}" ]]; then
          IFS='|' ios_provisioning_profile_urls_array=("${{ inputs.ios-provisioning-profile-urls }}")
        else
          IFS='|' ios_provisioning_profiles_base64_array=("${{ inputs.ios-provisioning-profiles-base64 }}")

          for i in "${!ios_provisioning_profiles_base64_array[@]}"
          do
              provisioning_profile_base64=${ios_provisioning_profiles_base64_array[$i]}
              echo -n "${provisioning_profile_base64}" | base64 --decode --output "${RUNNER_TEMP}/${i}.mobileprovision"
              ios_provisioning_profile_urls_array+=("file://${RUNNER_TEMP}/${i}.mobileprovision")
          done
        fi

        # shellcheck disable=SC2206
        args+=("--ios-provisioning-profile-urls" ${ios_provisioning_profile_urls_array[@]})

        if [[ -n "${{ inputs.ios-provisioning-profile-specifier }}" ]]; then
          args+=("--ios-provisioning-profile-specifier" "${{ inputs.ios-provisioning-profile-specifier }}")
        fi

        if [[ -n "${{ inputs.ios-team-id }}" ]]; then
          args+=("--ios-team-id" "${{ inputs.ios-team-id }}")
        fi

        if [[ -n "${{ inputs.ios-export-method }}" ]]; then
          args+=("--ios-export-method" "${{ inputs.ios-export-method }}")
        fi

        # -------
        # Caching
        # -------

        if [[ -n "${{ inputs.cache-provider }}" ]]; then
          if [[ "${{ inputs.cache-provider }}" == "github" ]]; then
            args+=("--cache-provider" "fs")
          else
            args+=("--cache-provider" "${{ inputs.cache-provider }}")
          fi
        fi

        # shellcheck disable=SC2154
        if [[ "${{ inputs.disable-cache }}" == "true" || "${{ inputs.disable-cache }}" == "yes" ]]; then
          args+=("--disable-cache")
        fi

        if [[ -n "${{ inputs.cache-env-var-lookup-keys }}" ]]; then
          IFS='|' cache_env_var_lookup_keys_value=("${{ inputs.cache-env-var-lookup-keys }}")
          # shellcheck disable=SC2206
          args+=("--cache-env-var-lookup-keys" ${cache_env_var_lookup_keys_value[@]})
        fi

        if [[ -n "${{ inputs.cache-file-lookup-paths }}" ]]; then
          IFS='|' cache_file_lookup_paths_value=("${{ inputs.cache-file-lookup-paths }}")
          # shellcheck disable=SC2206
          args+=("--cache-file-lookup-paths" ${cache_file_lookup_paths_value[@]})
        fi

        # shellcheck disable=SC2154
        if [[ "${{ inputs.disable-metro-cache }}" == "true" || "${{ inputs.disable-metro-cache }}" == "yes" ]]; then
          args+=("--disable-metro-cache")
        fi

        # -----
        # Hooks
        # -----

        if [[ -n "${{ inputs.pre-install-command }}" ]]; then
          args+=("--pre-install-command" "${{ inputs.pre-install-command }}")
        fi

        if [[ -n "${{ inputs.pre-build-command }}" ]]; then
          args+=("--pre-build-command" "${{ inputs.pre-build-command }}")
        fi

        if [[ -n "${{ inputs.post-build-command }}" ]]; then
          args+=("--post-build-command" "${{ inputs.post-build-command }}")
        fi

        # --------
        # Advanced
        # --------

        if [[ -n "${{ inputs.output-directory }}" ]]; then
          args+=("--output-directory" "${{ inputs.output-directory }}")
        fi

        # -------------------
        # Nitro Cli execution
        # -------------------

        BITRISE_STEP_VERSION=1.1.1
        BIN_FILE="nitro-macos"
        BIN_FILE_PATH="${RUNNER_TEMP}/nitro"

        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
        echo ${BIN_FILE_PATH} "${args[@]}"
        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

        exit_code=$?

        echo "exit code: ${exit_code}"
        ls ~/.nitro/cache

        mkdir -p ~/.nitro/cache >/dev/null 2>&1
        echo "${RANDOM}" > ~/.nitro/cache/${RANDOM}.txt
