name: "Sandbox"
description: "Sandbox Test"
branding:
  icon: "zap"
  color: "gray-dark"
inputs:
  file-content:
    description: File contents
runs:
  using: "composite"
  steps:
    - name: Install pgiz
      shell: bash
      run: brew install pigz
    # - name: Install fastlane
    #   shell: bash
    #   run: |
    #     curl -fL https://github.com/nitro-build/github-actions-sandbox/releases/download/1.0.0/fastlane.zip > /usr/local/bin/fastlane
    #     chmod +x /usr/local/bin/fastlane
    - name: Sample Script
      shell: bash
      run: |
        set -ex

        echo "pigz"
        pigz

        echo "fastlane --help"
        fastlane --help

        echo "command -v pigz"
        command -v pigz

        echo "echo "command -v pigz""
        command -v fastlane
