name: IOS
on: "push"
jobs:
  build:
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sandbox
        with:
          file-content: "this is some content updated"
